=== Suyoga28/TEcomp_Engineeing_Practicals/Web Tech/p3/volunteers.dtd
<!ELEMENT volunteers (volunteer+)>
<!ELEMENT volunteer (name, age, gender, role, experience)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT role (#PCDATA)>
<!ELEMENT experience (#PCDATA)>

=== Suyoga28/TEcomp_Engineeing_Practicals/Web Tech/p3/volunteers.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="volunteers.xsl"?>
<!DOCTYPE volunteers SYSTEM "volunteers.dtd">
<volunteers>
    <volunteer>
        <name>John Doe</name>
        <age>30</age>
        <gender>Male</gender>
        <role>Teacher</role>
        <experience>5 years</experience>
    </volunteer>
    <volunteer>
        <name>Jane Smith</name>
        <age>28</age>
        <gender>Female</gender>
        <role>Medical Assistant</role>
        <experience>3 years</experience>
    </volunteer>
</volunteers>
